# Generated by Django 4.0.3 on 2022-05-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_category_background_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(100, 'Admin'), (200, 'Read Write'), (300, 'Read Only')], default=300)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_categories', through='categories.CategoryAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoryaccess',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='categoryaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='categoryaccess',
            constraint=models.UniqueConstraint(fields=('category', 'user'), name='unique_category_access_through'),
        ),
    ]
