# Generated by Django 4.0.3 on 2022-07-24 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_categoryaccess_category_shared_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'category_invitations',
            },
        ),
        migrations.AddConstraint(
            model_name='categoryinvitation',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'category'), name='unique_category_invitation'),
        ),
        migrations.AddConstraint(
            model_name='categoryinvitation',
            constraint=models.CheckConstraint(check=models.Q(('sender', django.db.models.expressions.F('receiver')), _negated=True), name='sender_not_receiver'),
        ),
    ]
