# Generated by Django 4.1.2 on 2022-10-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_categoryinvitation_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinvitation',
            name='access_level',
            field=models.IntegerField(choices=[(100, 'Admin'), (200, 'Read Write'), (300, 'Read Only')], default=300),
        ),
        migrations.AddField(
            model_name='categoryinvitation',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
