# Generated by Django 3.2.8 on 2021-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('url', 'owner'), name='unique_link_owner'),
        ),
    ]
